### ISSUE TITLE
Create CONTRIBUTORS.md

### ISSUE THREAD

**Issue by Ckrielle** [Vishal643/propane#12]
Hello there. Looking at your README.md, it seems that the majority of it is dedicated to informing others how they can contribute. I believe it would be more clean, efficient, readable, and standardized if you created a CONTRIBUTORS.md file and moved the instructions there. You can then have a reference to it in the README.md. If you want I can take care of it.

**Comment by Vishal643** [comment]
Yeah Sure You can do that for me.
